version: "3"
services:
  backend:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - NODE_ENV=development

  frontend:
    build: ./client
    ports:
      - "3000:80"
    depends_on:
      - backend
    env_file:
      - .env.docker
    environment:
      - VITE_API_URL=${DOCKER_API_URL}
